[zh]
    locale    = "zh-cn"
    label     = "中文"
    direction = "ltr"
    title     = "wangcl"
    weight    = 1

[en]
    locale    = "en-us"
    label     = "English"
    direction = "ltr"
    title     = "wangcl"
    weight    = 2
