[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"
    weight     = 2
    [main.params]
        icon = "archives"

[[main]]
    identifier = "tags"
    name       = "标签"
    url        = "/tags/"
    weight     = 3
    [main.params]
        icon = "tag"

[[main]]
    identifier = "search"
    name       = "搜索"
    url        = "/search/"
    weight     = 4
    [main.params]
        icon = "search"

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/about/"
    weight     = 5
    [main.params]
        icon = "user"      

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/wangcl"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "RSS"
    name       = "RSS"
    url        = "/index.xml"
    [social.params]
        icon = "rss"
